language: ruby
rvm:
  - "2.3.3"

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database madloba_test;' -U postgres

script:
  - spring rspec spec
  - xvfb-run -a bundle exec rake cucumber
