language: ruby
rvm:
  - "2.2.2"

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database madloba_test;' -U postgres

script:
  - bundle exec rspec spec
  - bundle exec cucumber ./features WEBKIT=true
