language: ruby
rvm:
  - "2.2.4"

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database madloba_test;' -U postgres
  - gem install capybara-webkit

script:
  - bundle exec rspec spec
  - export DISPLAY=:99.0 && bundle exec rake cucumber
