version: '2'

services:
  web:
    build: .
    container_name: madloba_web
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - '.env.web'
  db:
    image: library/postgres:9.4.9
    ports:
      - "5431:5431"
    env_file:
      - '.env.db'
