FROM library/postgres:9.4.9
MAINTAINER Etienne Baqué <contact@madloba.org>

ARG password=defaultPassword
USER postgres
RUN /etc/init.d/postgresql start && psql --command "CREATE USER docker WITH SUPERUSER PASSWORD '$password';" && createdb -O docker docker

#ADD init.sh /docker-entrypoint-initdb.d/
#RUN chmod 0755 /docker-entrypoint-initdb.d/init.sh
#RUN echo "host all  all    0.0.0.0/0  md5" >> /var/lib/postgresql/pg_hba.conf
#RUN echo "listen_addresses='*'" >> /var/lib/postgresql/postgresql.conf
#EXPOSE 5432