version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    build: .
    command: bash -lc 'bundle exec puma -p 3000 -C config/puma.rb config.ru RAILS_ENV=production'
    volumes:
      - .:/var/www/madloba
    container_name: madloba_web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=madloba.local
    env_file:
      - '.env.web'
  db:
    image: library/postgres:9.4.9
    ports:
      - "5431:5431"
