version: '2'

services:
  web:
    build: .
    volumes:
      - .:/var/www/madloba
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
      - '.env.web'
  db:
    image: library/postgres:9.4.9
    volumes:
      - madloba-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - '.env.db'

volumes:
  madloba-postgres:
