default: &default
  # Set up your local environment variables in /config/app_environment_variables.rb
  # (you can rename the sample file provided in the same folder)
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  pool: 5
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV["MADLOBA_DEV_DATABASE"] %>
  username: <%= ENV["MADLOBA_DEV_USERNAME"] %>
  password: <%= ENV["MADLOBA_DEV_PASSWORD"] %>

development:
  <<: *default
  database: your_dev_db_name #CHANGE ME

test:
  <<: *default
  database: your_test_db_name #CHANGE ME

production:
  <<: *default
  database: your_production_db_name #CHANGE ME