development:
  # Set up your local environment variables in /config/app_environment_variables.rb
  # (you can rename the sample file provided in the same folder)
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["MADLOBA_DEV_DATABASE"] %>
  username: <%= ENV["MADLOBA_DEV_USERNAME"] %>
  password: <%= ENV["MADLOBA_DEV_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: madloba_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database:
  username:
  password: