default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV["MADLOBA_DEV_DATABASE"] %>
  password: <%= ENV["MADLOBA_DEV_PASSWORD"] %>
  username: <%= ENV["MADLOBA_DEV_USERNAME"] %>

test: &test
  <<: *default
  database: <%= ENV["MADLOBA_TEST_DATABASE"] %>
  password: <%= ENV["MADLOBA_TEST_PASSWORD"] %>
  username: <%= ENV["MADLOBA_TEST_USERNAME"] %>

production:
  <<: *default
  host: db
  database: madloba
  username: postgres
  password:

cucumber:
  <<: *test

