development:
  # Set up your local environment variables in /config/app_environment_variables.rb
  # (you can rename the sample file provided in the same folder)
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["MADLOBA_DEV_DATABASE"] %>
  username: <%= ENV["MADLOBA_DEV_USERNAME"] %>
  password: <%= ENV["MADLOBA_DEV_PASSWORD"] %>

test: &test
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["MADLOBA_TEST_DATABASE"] %>
  username: <%= ENV["MADLOBA_TEST_USERNAME"] %>
  password: <%= ENV["MADLOBA_TEST_PASSWORD"] %>

staging:
  # Deployment on a staging server: please indicate your database credentials here
  # (database name, username and password)
  adapter: postgresql
  encoding: unicode
  pool: 5
  database:
  username:
  password:

production:
  # Deployment on a production server: please indicate your database credentials here
  # (database name, username and password)
  adapter: postgresql
  encoding: unicode
  pool: 5
  database:
  username:
  password:

cucumber:
  <<: *test
