default: &default
  # Set up your local environment variables in /config/app_environment_variables.rb
  # (you can rename the sample file provided in the same folder)
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  password:
  username: postgres


development:
  <<: *default
  database: <%= ENV["MADLOBA_DEV_DATABASE"] %> #CHANGE ME

test:
  <<: *default
  database: your_test_db_name #CHANGE ME

production:
  <<: *default
  database: madloba #CHANGE ME