development:
  secret_key_base: <%= ENV["MADLOBA_DEV_SECRET_KEY_BASE"] %>
  smtp_host: localhost:3000
  smtp_address: localhost
  smtp_port: 1025
  smtp_username:
  smtp_password:
  smtp_authentication:
  notification_email: noreply@madloba.org
  error_sender_email: sender@test.com
  error_recipients_email: recipient@test.com

test:
  secret_key_base: <%= ENV["MADLOBA_DEV_SECRET_KEY_BASE"] %>
  smtp_host: localhost:3000
  smtp_address: localhost
  smtp_port: 1025
  smtp_username:
  smtp_password:
  smtp_authentication:
  notification_email:
  error_sender_email:
  error_recipients_email: []

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_host: <%= ENV["MADLOBA_SMTP_HOST"] %>
  smtp_address: <%= ENV["MADLOBA_SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["MADLOBA_SMTP_PORT"] %>
  smtp_username: <%= ENV["MADLOBA_SMTP_USERNAME"] %>
  smtp_password: <%= ENV["MADLOBA_SMTP_PASSWORD"] %>
  smtp_authentication: <%= ENV["MADLOBA_SMTP_AUTHENTICATION"] %>
  notification_email: <%= ENV['MADLOBA_NOTIFICATION_EMAIL'] %>
  error_sender_email: <%= ENV["MADLOBA_ERROR_SENDER"] %>
  error_recipients_email: <%= ENV["MADLOBA_ERROR_RECIPIENTS"] %>
